'use strict';
const $=id=>document.getElementById(id), nf=new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0});
const money=n=>Number.isFinite(n)?(Math.abs(n)<100?new Intl.NumberFormat('ko-KR',{maximumSignificantDigits:7}).format(n):nf.format(n)):'—';
const pct=n=>Number.isFinite(n)?`${n>0?'+':''}${(n*100).toFixed(2)}%`:'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sign=n=>n>0?'up':n<0?'down':'';
let markets=[],selected='KRW-BTC',unit=15,candles=[],engine=null,marketBusy=false,engineBusy=false,chartSeq=0,toastTimer;
async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'연결에 실패했습니다.');return d;}
function text(id,value){$(id).textContent=value;}
function toast(s){text('toast',s);$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500);}
function showView(view){document.querySelectorAll('.view').forEach(e=>e.classList.toggle('hidden',e.id!==`${view}-view`));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.view===view));if(view==='trading')drawChart();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function renderMarkets(){const term=$('search').value.trim().toLowerCase();const rows=markets.filter(m=>`${m.market} ${m.korean_name} ${m.english_name}`.toLowerCase().includes(term));text('market-count',`${markets.length} 종목`);$('market-list').innerHTML=rows.length?rows.map(m=>`<button class="market-row ${m.market===selected?'active':''}" data-market="${esc(m.market)}" aria-pressed="${m.market===selected}"><span class="coin">${esc(m.market.slice(4,6))}</span><span class="coin-names"><b>${esc(m.korean_name||m.market)}</b><small>${esc(m.market.slice(4))}</small></span><span class="market-price"><b>${money(m.trade_price)}</b><small class="${sign(m.signed_change_rate)}">${pct(m.signed_change_rate)}</small></span></button>`).join(''):'<p class="empty">검색 결과가 없습니다.</p>';}
$('search').oninput=renderMarkets;
$('market-list').onclick=e=>{const b=e.target.closest('[data-market]');if(b)selectMarket(b.dataset.market);};
function selectMarket(m){selected=m;renderMarkets();renderQuote();renderSignal();loadChart();}
function renderQuote(){const m=markets.find(m=>m.market===selected);if(!m)return;text('coin-name',m.korean_name||selected);text('coin-market',`${selected.slice(4)} / KRW`);text('coin-icon',selected.slice(4,5));text('price',money(m.trade_price));text('change',pct(m.signed_change_rate));$('change').className=sign(m.signed_change_rate);text('high',money(m.high_price));text('low',money(m.low_price));text('volume',`${(m.acc_trade_price_24h/1e8).toFixed(1)}억`);$('upbit-link').href=`https://upbit.com/exchange?code=CRIX.UPBIT.${selected}`;}
async function loadMarkets(){if(marketBusy)return;marketBusy=true;try{const d=await api('/api/markets');markets=d.markets;renderMarkets();renderQuote();text('market-status',`시세 갱신 ${new Date(d.at).toLocaleTimeString('ko-KR',{hour12:false})}`);$('notice').classList.remove('error');if(!engine?.connected)text('notice','실시간 시세가 연결되었습니다. 엔진을 연결하면 모의매매·실거래 상태를 이 화면에서 확인하고 제어할 수 있습니다.');}catch(e){text('market-status','시세 연결 오류');text('notice',e.message+' 표시된 시세가 있다면 이전 조회 값입니다.');$('notice').classList.add('error');}finally{marketBusy=false;}}
document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{unit=Number(b.dataset.unit);document.querySelectorAll('[data-unit]').forEach(e=>e.classList.toggle('selected',e===b));loadChart();});
async function loadChart(){const seq=++chartSeq;text('chart-message','차트 불러오는 중');$('chart-message').classList.remove('hidden');try{const d=await api(`/api/candles?market=${selected}&unit=${unit}`);if(seq!==chartSeq)return;candles=d.candles;if(!candles.length)throw new Error('표시할 캔들이 없습니다.');$('chart-message').classList.add('hidden');text('chart-time',`${unit}분봉 · 최근 ${candles.length}개`);drawChart();}catch(e){if(seq===chartSeq)text('chart-message',e.message);}}
function drawChart(){const canvas=$('chart'),rect=canvas.getBoundingClientRect();if(!rect.width||!candles.length)return;const dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const w=rect.width,h=rect.height,pad=15,right=94,top=16,bottom=h-71,plot=w-pad-right;const min=Math.min(...candles.map(r=>r.low_price)),max=Math.max(...candles.map(r=>r.high_price));const range=(max-min)||max*.01||1,lo=min-range*.08,hi=max+range*.08;const y=v=>top+(hi-v)/(hi-lo)*(bottom-top);c.font='12px system-ui';for(let i=0;i<5;i++){const value=lo+(hi-lo)*i/4,yy=y(value);c.strokeStyle='#252b3444';c.beginPath();c.moveTo(pad,yy);c.lineTo(w-right,yy);c.stroke();c.fillStyle='#707c8e';c.fillText(money(value),w-right+9,yy+4);}const step=plot/candles.length,bw=Math.max(1,step*.62),vmax=Math.max(...candles.map(r=>r.candle_acc_trade_volume))||1;candles.forEach((r,i)=>{const x=pad+step*(i+.5),up=r.trade_price>=r.opening_price;c.fillStyle=c.strokeStyle=up?'#f67783':'#74a2ff';c.beginPath();c.moveTo(x,y(r.high_price));c.lineTo(x,y(r.low_price));c.stroke();c.fillRect(x-bw/2,Math.min(y(r.opening_price),y(r.trade_price)),bw,Math.max(1,Math.abs(y(r.trade_price)-y(r.opening_price))));c.globalAlpha=.25;const vh=r.candle_acc_trade_volume/vmax*33;c.fillRect(x-bw/2,h-23-vh,bw,vh);c.globalAlpha=1;if(i%Math.ceil(candles.length/4)===0){c.fillStyle='#657084';c.fillText(r.candle_date_time_kst.slice(11,16),x,h-5);}});const last=candles.at(-1).trade_price;c.setLineDash([3,4]);c.strokeStyle='#b7f36766';c.beginPath();c.moveTo(pad,y(last));c.lineTo(w-right,y(last));c.stroke();c.setLineDash([]);c.fillStyle='#b7f36a';c.fillRect(w-right+3,y(last)-9,right-6,18);c.fillStyle='#16220c';c.fillText(money(last),w-right+8,y(last)+4);}
new ResizeObserver(drawChart).observe($('chart'));
function renderSignal(){const s=engine?.live?.markets?.[selected];const regime={bull_trend:'상승 추세',bear_trend:'하락 추세',range:'횡보',dead:'낮은 변동성',chaos:'과열'};text('signal-tag',s?({buy:'진입 신호',sell:'청산 신호',hold:'대기'}[s.action]||'대기'):'대기');text('signal-reason',s?.reason||(engine?.armed===false?'실거래 시작 대기 중입니다. 아직 매매 신호를 평가하지 않습니다.':'자동매매 엔진을 연결하면 종목별 진입·대기 사유가 표시됩니다.'));text('regime',regime[s?.regime]||'—');text('atr',s?.atr_pct!=null?pct(s.atr_pct):'—');text('rsi',s?.rsi!=null?s.rsi.toFixed(1):'—');text('vol-ratio',s?.vol_ratio!=null?`${s.vol_ratio.toFixed(2)}×`:'—');}
function metric(id,n,suffix){$(id).innerHTML=`${money(n)}<em>${suffix}</em>`;}
function renderEngine(){const connected=!!engine?.connected,state=engine?.state,live=engine?.live,mode=state?.mode,healthy=connected&&engine?.running&&!engine?.stale,paused=!!state?.kill,awaiting=mode==='live'&&engine?.armed===false,canStart=healthy&&(mode!=='live'||engine?.checks?.ok);const action=$('engine-action');$('engine-dot').classList.toggle('connected',healthy);text('engine-title',!connected?'연결 대기':!healthy?'엔진 확인 필요':awaiting?'실거래 시작 대기':paused?'신규 진입 중단':'엔진 운용 중');text('engine-detail',!connected?'실행 서버를 연결해 주세요':engine?.halted_reason||(engine?.checks?.ok===false?engine.checks.message:'')||(!healthy?'마지막 평가 시각을 확인해 주세요':awaiting?'직접 시작하기 전에는 주문하지 않습니다':paused?'보유 포지션의 청산은 계속됩니다':'시그널과 운용 한도에 따라 평가 중'));text('engine-mode',mode==='live'?'실거래':mode==='paper'?'모의매매':'미연결');text('balance-mode',mode==='live'?'실제 계좌':mode==='paper'?'모의 자산':'엔진 미연결');text('connection-engine',connected?'연결됨':'미연결');text('connection-keys',engine?.keys_configured?'서버에 설정됨':'설정 필요');text('connection-check',engine?.checks?.ok?'통과':engine?.checks?'점검 필요':'확인 전');action.disabled=!connected||(paused&&!canStart);action.textContent=!connected?'엔진 연결 필요':paused&&!canStart?'연결 점검 필요':paused?(mode==='live'?'실거래 시작':'모의매매 시작'):'신규 매수 중단';action.dataset.action=paused?'resume':'pause';text('strategy',state?.engine?.entry_mode||'—');text('watching',live?.watching?.length?`${live.watching.length}종목`:'—');text('interval',state?.engine?.candle_unit?`${state.engine.candle_unit}분봉`:'—');text('last-tick',engine?.last_tick?new Date(engine.last_tick).toLocaleTimeString('ko-KR',{hour12:false}):'—');text('max-order',state?.risk?`${money(state.risk.max_order_krw)}원`:'—');text('loss-limit',state?.risk?pct(-state.risk.daily_loss_limit):'—');text('trade-limit',state?.risk?`${state.risk.daily_trade_limit}회`:'—');text('breakeven',state?.cost?pct(state.cost.breakeven):'—');metric('total',state?.equity?.total,'KRW');metric('pnl',state?.performance?.net_pnl,'KRW');metric('positions-count',state?.positions?.length,'종목');metric('trades-count',state?.performance?.trades,'건');text('fees',state?.performance?`누적 수수료 ${money(state.performance.fees_paid)}원`:'누적 수수료 —');text('equity-sub',state?.equity?`현금 ${money(state.equity.cash)}원 · 투자 ${money(state.equity.exposure)}원`:'연결 후 계좌 상태를 확인할 수 있습니다');text('position-badge',state?.positions?.length||0);$('pnl').className=sign(state?.performance?.net_pnl);if(connected){text('notice',`${mode==='live'?'실거래':'모의매매'} 엔진 ${healthy?'연결됨':'상태 확인 필요'} · ${awaiting?'시작 대기 중입니다. 매수·매도 주문은 실행되지 않습니다.':paused?'신규 진입이 중단되어 있습니다. 보유 포지션 청산은 계속 평가합니다.':'실행 서버에서 자동매매가 동작합니다.'}`);$('notice').classList.toggle('error',!healthy);}else if(engine?.error){text('notice',engine.error);$('notice').classList.add('error');}renderTables();renderSignal();}
const exitLabel={stop:'손절',take_profit:'목표 도달',trail:'트레일링',time:'보유시간 초과',regime:'추세 이탈',session_close:'세션 종료'};
function renderTables(){const positions=engine?.state?.positions||[],trades=engine?.state?.trades||[];$('positions-body').innerHTML=positions.length?positions.map(p=>`<tr><td><b>${esc(p.market)}</b></td><td>${money(p.entry_price)}</td><td>${Number(p.qty).toFixed(8)}</td><td class="${sign(p.net_pnl)}">${money(p.net_pnl)}원 (${pct(p.net_return)})</td><td>${money(p.stop_price)}</td><td>${p.armed?'트레일링 활성':'보유 중'}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">${engine?.connected?'현재 보유 중인 포지션이 없습니다. 진입 조건 충족 시 기록됩니다.':'엔진 연결 후 보유 포지션이 표시됩니다.'}</td></tr>`;$('history-body').innerHTML=trades.length?trades.map(t=>`<tr><td>${esc(t.closed_at.replace('T',' '))}</td><td>${esc(t.market)}</td><td>${money(t.entry_price)}</td><td>${money(t.exit_price)}</td><td class="${sign(t.net_pnl)}">${money(t.net_pnl)}원</td><td class="${sign(t.net_return)}">${pct(t.net_return)}</td><td>${esc(exitLabel[t.exit_kind]||t.exit_kind)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">청산된 거래가 없습니다.</td></tr>';$('export').disabled=!trades.length;}
async function loadEngine(){if(engineBusy)return;engineBusy=true;try{engine=await api('/api/engine');}catch(e){engine={connected:false,error:e.message};}finally{engineBusy=false;renderEngine();}}
async function control(action,confirm=''){const button=$('engine-action');button.disabled=true;try{const d=await api('/api/control',{action,confirm,requestId:crypto.randomUUID()});if(d.error||d.connected===false)throw new Error(d.error||d.message);toast(action==='pause'?'신규 매수를 중단했습니다. 보유 포지션 청산은 계속됩니다.':'신규 진입을 시작했습니다.');}catch(e){toast(e.message);}finally{await loadEngine();}}
$('engine-action').onclick=()=>{const action=$('engine-action').dataset.action;if(action==='resume'&&engine?.state?.mode==='live'){text('confirm-limits',`1회 최대 ${money(engine.state.risk.max_order_krw)}원 · 일일 진입 ${engine.state.risk.daily_trade_limit}회 · 손실 한도 ${pct(-engine.state.risk.daily_loss_limit)}`);$('confirm-text').value='';$('confirm-live').disabled=true;$('confirm-dialog').showModal();}else control(action);};
$('confirm-text').oninput=()=>{$('confirm-live').disabled=$('confirm-text').value!=='실거래 시작';};$('confirm-dialog').addEventListener('close',()=>{if($('confirm-dialog').returnValue==='confirm'&&$('confirm-text').value==='실거래 시작')control('resume','실거래 시작');});
$('check').onclick=async()=>{$('check').disabled=true;text('check-result','계좌·주문 조회 권한을 점검하고 있습니다.');try{const d=await api('/api/check',{});text('check-result',d.message||(d.ok?'연결 점검을 통과했습니다.':'엔진 설정을 확인해 주세요.'));await loadEngine();}catch(e){text('check-result',e.message);}finally{$('check').disabled=false;}};
$('export').onclick=()=>{const fields=['closed_at','market','entry_price','exit_price','net_pnl','net_return','exit_kind'];const rows=[fields,...(engine?.state?.trades||[]).map(t=>fields.map(k=>t[k]))];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`ubbit-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('refresh').onclick=()=>{loadMarkets();loadEngine();loadChart();};
setInterval(()=>{text('clock',new Date().toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})+' KST');},1000);
setInterval(()=>{if(!document.hidden){loadMarkets();loadEngine();}},15000);setInterval(()=>{if(!document.hidden)loadChart();},60000);
loadMarkets();loadEngine();loadChart();
// Feature-detected WebMCP: reading and navigating only. Trading starts in UI.
async function registerTools(){
  const context=document.modelContext||navigator.modelContext;
  if(!context?.registerTool)return;
  await context.registerTool({name:'ubbit_status',description:'현재 화면의 엔진 연결 상태와 선택 종목 시세를 읽습니다. 주문하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,consequentialHint:false},execute:async()=>JSON.stringify({market:markets.find(m=>m.market===selected)||null,engine:engine?.connected?{mode:engine.state?.mode,running:engine.running,stale:engine.stale,last_tick:engine.last_tick,paused:engine.state?.kill}:{connected:false}})});
  await context.registerTool({name:'ubbit_select_market',description:'현재 원화 마켓에서 종목을 선택해 차트를 표시합니다. 주문이나 엔진 설정은 변경하지 않습니다.',inputSchema:{type:'object',properties:{market:{type:'string',description:'KRW-BTC 같은 원화 마켓 코드'}},required:['market'],additionalProperties:false},annotations:{readOnlyHint:false,consequentialHint:false},execute:async({market})=>{if(!markets.some(m=>m.market===market))throw new Error('현재 마켓 목록에 없는 종목입니다.');showView('trading');selectMarket(market);return JSON.stringify({selected:market});}});
}
registerTools().catch(()=>{});
